static void duckhunt_message (char *message);
static void draw_aimer (int x, int y);
static void aimer_hold (int x, int y);
static void aimer_shoot (int x, int y);
static void startup_screen ();
static void duckhunt_bar ();
static void dog_holdduck ();
static void dog_laughing ();
static void duck_flyaway ();
static void next_round ();
static void duck_shot ();
static void dog_walk ();
static void move_duck ();
static void reset_duckhunt();
static void duckhunt_setup();
static void reset_round();
static void move_duck();
static void init_duck();
static void hit_action();
static void move_up();
static void move_down();
static void move_left();
static void move_right();
