#!/bin/sh

# ZeroSlackr Framework's Loop-Mount Script
# Last updated: July 24, 2008
# ~Keripo
#
# Note: This file must be saved in UNIX format.
# Advanced text editors like Notepad++, KWrite
# and even Podwrite work. Do NOT use Notepad!
# To disable a line, place a "#" infront of it.
# IF YOU ARE ON LINUX, DO NOT FORGET TO CHECK
# THIS FILE'S PERMISSIONS! To make sure, use:
# "chmod ugo+rwx rc" (modified accordingly)

# Loop-mount ZeroSlackr userland
busybox mount -t ext3 -o loop,rw /boot/userland.ext3 /boot/mount

# Swap roots
cd /boot/mount/
busybox pivot_root . mnt
clear

# Execute normal rc file
# Can't figure out minix's syntax for loops
NUM="1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17"
for n in $NUM; do
  echo 
done
sh /etc/rc
