#!/bin/sh

# ZeroSlackr Framework's Loop-Mount Script
# Last updated: Mar 15, 2009
# ~Keripo
#
# Note: This file must be saved in UNIX format.
# Advanced text editors like Notepad++, KWrite
# and even Podwrite work. Do NOT use Notepad!
# To disable a line, place a "#" infront of it.
# IF YOU ARE ON LINUX, DO NOT FORGET TO CHECK
# THIS FILE'S PERMISSIONS! To make sure, use:
# "chmod ugo+rwx rc" (modified accordingly)

# Loop-mount ZeroSlackr userland
busybox mount -t ext2 -o loop,rw /boot/userland.ext2 /boot/mount

# Swap roots
cd /boot/mount/
busybox pivot_root . mnt

# Execute normal rc file
# Lots of lines are echo'd so that text is visible
# rather than only the first line being shown
# (due to an odd minix bug that I don't userstand)
NUM="1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20"
for n in $NUM; do
  echo 
done
sh /etc/rc

# Just in case
echo "Error!"
echo "Loop-mount startup failed!"
echo "Now rebooting..."
busybox reboot
