--- Makefile	2008-07-08 15:07:04.000000000 +0000
+++ Makefile	2008-07-08 15:16:21.000000000 +0000
@@ -146,6 +146,9 @@
 INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
 INTERFACE_AGE = 5
 LDFLAGS = 
+DEFS += -DLOAD_JPG=1 -DLOAD_PNG=1 -DLOAD_TIFF=1
+CPPFLAGS += -I$(PWD)/../SDL_image/../libjpeg/include -I$(PWD)/../SDL_image/../zlib/include -I$(PWD)/../SDL_image/../libpng/include -I$(PWD)/../SDL_image/../libtiff/include
+LDFLAGS += -L$(PWD)/../SDL_image/../libjpeg/lib -ljpeg -L$(PWD)/../SDL_image/../zlib/lib -lz -L$(PWD)/../SDL_image/../libpng/lib -lpng -L$(PWD)/../SDL_image/../libtiff/lib -ltiff -elf2flt
 LIBOBJS = 
 LIBS =  -L/root/iPL/libs/SDL/lib -lSDL
 LIBTOOL = $(SHELL) $(top_builddir)/libtool
