\name Halloween 2006
# A special scheme for October 31, 2006
# by Keripo
# Generated by iPL Color Scheme Editor

menu:
	bg => #FF00FF,
	fg => #ffffff,
	choice => #000000,
	icon => #000000,
	selbg => <horiz #000000 to #FF8000>,
	selfg => #FF8000,
	selchoice => #FF8000,
	icon0 => #351B00,
	icon3 => #FF8000,
	icon1 => #6C3600,
	icon2 => #AA5500
scroll:
	box => #000000,
	bar => <horiz #FF8000 to #000000>,
	bg => <horiz #000000 to #370000>
header:
	line => #000000,
	bg => @halloween/CandyMenuBarColour.png b@halloween/CandyMenuBarMono.png m@halloween/CandyMenuBarMono.png p@halloween/CandyMenuBarColour.png n@halloween/CandyMenuBarColour.png v@halloween/CandyMenuBarColour.png,
	fg => #FF8000,
	gradient.top => #000000,
	gradient.bottom => #FF8000,
	gradient.middle => #FF8000,
	gradient.bar => <vert #000000 to #FF8000>,
	accent => #000000,
	shadow => #000000,
	shine => #FF8000
window:
	bg => @halloween/PumpkinBackgroundPhoto.png b@halloween/PumpkinBackgroundMono.png m@halloween/PumpkinBackgroundMini.png p@halloween/PumpkinBackgroundPhoto.png n@halloween/PumpkinBackgroundNano.png v@halloween/PumpkinBackgroundVideo.png,
	fg => #FF8000,
	border => #FF8000
music:
	bar.bg => <vert #530000 to #000000>,
	bar => <vert #000000 to #FF8000>
loadavg:
	bg => #000000,
	fg => @halloween/PumpkinLoadAvg.png,
	spike => #FF8000
lock:
	fill => #FF8000,
	border => #000000
battery:
	border => #000000,
	bg => @halloween/MoonBatteryIcon.png,
	fill.normal => <vert #000000 to #FF8000>,
	bg.low => #FF0000,
	fill.low => <vert #FF0000 to #FF8000>,
	bg.charging => <vert #000000 to #FFFF00>,
	fill.charge => <vert #FF8000 to #FFFF00>,
	chargingbolt => #FF8000
box:
	default.bg => #000000,
	default.fg => #FF8000,
	default.border => #FF8000,
	selected.bg => #FF8000,
	selected.fg => #000000,
	selected.border => #000000,
	special.bg => <vert #000000 to #000000 to #FF8000>,
	special.fg => #FF8000,
	special.border => #FF8000
button:
	default.bg => #000000,
	default.fg => #FF8000,
	default.border => #FF8000,
	selected.bg => <vert #000000 to #000000 to #FF8000>,
	selected.fg => #FF8000,
	selected.border => #FF8000
input:
	bg => #000000,
	fg => #FF8000,
	selbg => #FF8000,
	selfg => #000000,
	border => #FF8000,
	cursor => #FF8000
textarea:
	bg => #000000,
	fg => #FF8000
slider:
	border => #000000,
	full => <vert #000000 to #FF8000>,
	bg => <vert #370000 to #000000>
dialog:
	bg => #000000,
	fg => #FF8000,
	line => #800000,
	title.fg => #FF8000,
	button.bg => #000000,
	button.fg => #FF8000,
	button.border => #FF8000,
	button.sel.bg => #000000,
	button.sel.fg => #FF8000,
	button.sel.border => #FF8000,
	button.sel.inner => #FF8000
error:
	bg => #000000,
	fg => #FF8000,
	line => #800000,
	title.fg => #FF8000,
	button.bg => #000000,
	button.fg => #FF8000,
	button.border => #FF8000,
	button.sel.bg => #000000,
	button.sel.fg => #FF8000,
	button.sel.border => #FF8000,
	button.sel.inner => #FF8000
